# Generated by Django 3.2.7 on 2022-04-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_no',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
