# Generated by Django 3.2.7 on 2022-05-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Browse_Categories',
        ),
    ]
