# Generated by Django 3.2.7 on 2022-04-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
