# Generated by Django 3.2.7 on 2022-04-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220425_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_no',
        ),
        migrations.AddField(
            model_name='item',
            name='item',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
