# Generated by Django 3.2.7 on 2022-04-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220428_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default=None, max_length=500, null=True)),
                ('matt', models.CharField(default=None, max_length=500, null=True)),
                ('brian', models.CharField(default=None, max_length=500, null=True)),
            ],
        ),
    ]
