# Generated by Django 3.2.7 on 2022-04-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='brian',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='company',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='matt',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
