# Generated by Django 3.2.7 on 2022-04-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220428_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='brian',
            new_name='bryan',
        ),
    ]
