# Generated by Django 3.2.7 on 2022-04-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.TextField(default=None),
        ),
    ]
