# Generated by Django 3.2.7 on 2022-05-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_brian_about_bryan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, null=True)),
                ('body', models.CharField(default=None, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='bryan_picture',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='about',
            name='matt_picture',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
