# Generated by Django 3.2.7 on 2022-05-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_contract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.AlterField(
            model_name='testimony',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
