# Generated by Django 3.2.7 on 2022-05-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220502_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(default=None, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=None, max_length=100, null=True)),
                ('phone', models.CharField(default=None, max_length=20, null=True)),
                ('email', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
    ]
